kind: Deployment
apiVersion: apps/v1
metadata:
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: datauserclient
        image: ghcr.io/mohammad-nassar10/datauserclient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always
